app/routes.py
from datetime import datetime, timedelta, timezone

from flask import Flask, request, session, render_template, redirect, url_for, flash, Blueprint
from flask_login import current_user, logout_user, login_required, login_user
from app import db
from app.models import *
from app.forms import LoginForm, RegistrationForm, AddMonitorForm, ZipKeyForm

bp = Blueprint("main", __name__)

"""
defines routes used for flask app

this is defined as a blueprint to allow this project
to use the flask factory pattern project structure

webpages are made as templates using the jinja templating engine.
the templates are filled out before being sent to the user as pure html
"""

@bp.after_request
def after_request(response):
    
    # the website is not cached to prevent accessing pages that need authentication
    # after logging out due to the pages being cached
    response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0, max-age=0'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '-1'

    return response

@bp.route("/")
def index():
    return render_template("index.html")

@bp.route("/login", methods=['GET', 'POST'])
def login():

    # setting session to permanent allows a timeout to be set
    # in this case the timeout is set to an hour in the config file
    session.permanent = True

    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    form = LoginForm()
    if form.validate_on_submit():

        user = db.session.scalar(sa.select(User).where(User.username == form.username.data))
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("main.login"))
        
        login_user(user)
    
        return redirect(url_for("main.dashboard"))
    

    return render_template("login.html", form=form)

@bp.route("/logout")
def logout():
    # session cookies are cleared to prevent authentication session cookie
    # from being stored for longer tha neccessary
    session.clear()
    logout_user()
    return redirect(url_for("main.index"))

@bp.route("/register", methods=["GET", "POST"])
def register():

    # user shouldn't be able to register if they are
    # already logged in
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))
    
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()

        flash("You can now log in")

        return redirect(url_for("main.login"))

    return render_template("register.html", form=form)

@bp.route("/dashboard")
@login_required
def dashboard():

    # get all monitors belonging to current user
    monitors: list[Monitor] = db.session.scalars(
        current_user.monitors.select()
    ).all()

    # get most recent status check for monitors that belong to the current user
    most_recent_statuses: list[Status] = []
    for m in monitors:
        most_recent = db.session.scalars(
            m.status_checks.select().order_by(sa.desc(Status.timestamp))
        ).first()
        most_recent_statuses.append(most_recent)

    # pass monitor and status information to template
    monitor_and_status = list(zip(monitors, most_recent_statuses))
    return render_template("dashboard.html", monitor_and_status=monitor_and_status)

@bp.route("/dashboard/add_monitor", methods=["GET", "POST"])
@login_required
def add_monitor():

    form = AddMonitorForm()

    if form.validate_on_submit():

        existing_monitor = db.session.scalar(
            sa.select(Monitor).where(sa.and_(Monitor.user_id == current_user.id, Monitor.url == form.url.data))
        )

        # don't add monitors that already exist
        if existing_monitor is not None:
            flash("Monitor already exists")
            return redirect(url_for("main.add_monitor"))

        seconds_to_next_ping = 60*form.minutes_between_pings.data
        time_next_ping = datetime.now(timezone.utc) + timedelta(seconds=seconds_to_next_ping)

        monitor = Monitor(url=form.url.data, time_next_ping=time_next_ping, seconds_to_next_ping=seconds_to_next_ping, user=current_user)

        db.session.add(monitor)
        db.session.commit()

        return redirect(url_for("main.dashboard"))

    return render_template("add_monitor.html", form=form)

@bp.route("/dashboard/remove_monitor/<monitor_id>")
@login_required
def remove_monitor(monitor_id):

    to_delete = db.session.get(Monitor, monitor_id)

    # if monitor belongs to user
    # we don't want to be able to delete monitors belonging to other uses
    if (to_delete is not None) and to_delete.user_id == current_user.id:
        db.session.delete(to_delete)
        db.session.commit()

    return redirect(url_for("main.dashboard"))

@bp.route("/account_settings")
@login_required
def account_settings():

    form = ZipKeyForm()

    return render_template("settings.html", form=form)

@bp.route("/account_settings/set_zip_key", methods=["POST"])
@login_required
def set_zip_key():
    
    zip_key = request.form.get("zip_key")

    if zip_key is None:
        current_user.zip_key = None
    else:
        if not zip_key.isspace():
            current_user.zip_key = zip_key

    db.session.commit()
    
    return redirect(url_for("main.account_settings"))

app/templates/add_monitor.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            body{
                background-color: lightsteelblue;
            }
            h1{
                font-size: 72px;
                text-align: center;
                display: table;
                padding-left: 24px;
                padding-right: 24px;
                margin: auto;
                border: thick solid rgb(150, 180, 218);
                background-color:aliceblue;
                font-family: 'Times New Roman', Times, serif;
            }
            .textEntry{
                display: table;
                margin: auto;
                font-size: 24px;
                font-weight: bold;
                padding-left: 10px;
                padding-right: 10px;
            }
            .submit{
                display: table;
                margin: auto;
            }
            #submit{
            background-color: aliceblue;
            border: solid rgb(127,165,215);
            border-radius: 5px;
            color: black;
            padding: 5px 22px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 24px;
            margin: 4px 2px;
            cursor: pointer;
            font-family: 'Times New Roman', Times, serif;
            }

            .msg{
            display: table;
            margin: auto;
            color: rgb(235, 36, 36);
            padding: 10px;
            border-radius: 20px;
            background-color: rgb(252, 200, 200);
            border: thick solid red;
            font-weight: bolder;
            }

            #submit:hover {
                background-color: rgb(170, 170, 170);
            }   
            #minutes_between_pings{
                background-color: aliceblue;
            }
            #url{
                background-color: aliceblue;
            }
            .backButton{
                border:solid rgb(127,165,215);
                background-color: aliceblue;
                border-radius: 10px;
                margin : auto;
                display: table;
                padding: 10px;
                font-size: 24px;
                font-family: 'Times New Roman', Times, serif;
                color: black;
                text-decoration: none;
            }
        </style>
    </head>

    <body>

        <h1>Add Servers Here!</h1>

        <!--<p>Adding monitor for {{ current_user.username }}</p>-->

        {% with messages = get_flashed_messages() %}

        {% if messages %}
        
            <div class = "msg">

            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}

        </div>
       
        {% endif %}
        {% endwith %}

        {% for error in form.url.errors %}
                <span style="display: table;margin: auto;color: rgb(235, 36, 36);padding: 10px;background-color: rgb(252, 200, 200);border: thick solid red;font-weight: bolder;">[{{ error }}]</span>
                {% endfor %}

        <form method="post">
            <br>
            {{ form.hidden_tag() }}
            <div class = "textEntry" style="background-color: aliceblue; border: thick solid rgb(129, 169, 221);">
                <p>
                {{ form.url.label }}<br>
                {{ form.url(size=32) }}<br>
                </p>
                <p>
                    {{ form.minutes_between_pings.label }}<br>
                    {{ form.minutes_between_pings(size=32) }}<br>
                    {% for error in form.minutes_between_pings.errors %}
                    <span style="display: table;margin: auto;color: rgb(235, 36, 36);padding: 10px;border-radius: 20px;background-color: rgb(252, 200, 200);border: thick solid red;font-weight: bolder;">[{{ error }}]</span>
                {% endfor %}
                </p>
            </div>
            <div class="submit">
            <p>{{ form.submit() }}</p>
            </div>
        </form>

        <p> <a class="backButton" href="{{ url_for('main.dashboard') }}">Return To Dashboard</a> </p>

    </body>


</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            h1{
                font-size: 72px;
                text-align: center;
                display: table;
                padding-left: 24px;
                padding-right: 24px;
                margin: auto;
                border: thick solid rgb(150, 180, 218);
                background-color:aliceblue;
            }
            .serverListHead{
            display: table;
            margin: auto;
            color: black;
            padding: 10px;
            padding-left: 75px;
            padding-right: 75px;
            
            background-color:aliceblue;
            border: thick solid rgb(150, 180, 218);
            

            font-size: 32px;
            }
            .serverList{
                display: table;
                margin: auto;
                padding-top: 1.5%;
                padding-left: 5%;
                padding-right: 5%;
                padding-bottom: 2.5%;
                
                background-color: aliceblue;
                border: thick solid rgb(150, 180, 218);
                font-size: 32px;
            }

            .welcome{
            display: table;
            margin: auto;
            color: black;
            padding: 20px;
            
            background-color:aliceblue;
            border: thick solid rgb(150, 180, 218);
            

            font-size: 32px;
            }
            .alert_NoServers{
                display: table;
            margin: auto;
            color: red;
            padding: 10px;
            
            background-color:aliceblue;
            
            font-weight: bolder;

            font-size: 18px;
            }
            body{
                background-color: lightsteelblue;
            }
            .buttons{
                display: table;
                margin: auto;
                padding: 20px;
            }
            .childButton{
                display: inline-block;
                padding: 20px;
                border: thick solid rgb(116, 161, 220) ;
                background-color: white;
                border-radius: 10px;
                margin : 100px;
                
                font-size: 40px;
                font-family: 'Times New Roman', Times, serif;
                
               
                
            }
            .button{
                text-decoration: none;
                color: black;
            }
            .remove{
                text-align: right;
            }
            .serverName{
                text-align: left;
            }
        </style>
    </head>

    <body>

        <h1>Your Servers</h1>
        <br>

        <p class = "welcome">Hello {{ current_user.username }}</p>

        
        <div class = 'buttons'>
            <div class = 'childButton'><a class="button" href="{{ url_for('main.add_monitor') }}">Add Server</a></div>
            <div class = 'childButton'><a class ="button" href="{{ url_for('main.account_settings') }}">Account Settings</a></div>
            <div class = 'childButton'><a class ="button" href="{{ url_for('main.logout') }}">Logout</a></div>

        </div>
        
        <p class = 'serverListHead'>Server List</p>
        <div class = "serverList">
        {% if monitor_and_status %}
        {% for (monitor, status) in monitor_and_status %}
        
        <div >
                <p style="margin:0;display:inline;float:left;padding-bottom: 50px">{{ monitor.url }} </p>
                <p style="margin:0;display:inline;float:right;padding-left: 500px;padding-bottom: 50px;"><a  href="{{ url_for('main.remove_monitor', monitor_id=monitor.id) }}">remove</a></p>
                
                <br>
                <br>
                <p style="font-size: small;">Last Checked {{ status.timestamp }}</p>
            </p>
    
        {% endfor %}

        {% else %}
        <p class = 'alert_NoServers'>You currently aren't monitoring any servers! Add servers by clicking the add server button! </p>
        {% endif %}

    </div>

    </body>


</html>

app/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            .myDiv{
               
                text-align : center;
            }
            a{
                border: thick solid rgb(127, 165, 215) ;
                background-color: white;
                border-radius: 10px;
                margin : 100px;
                padding: 10px;
                font-size: 40px;
                font-family: 'Times New Roman', Times, serif;
                color: black;
                text-decoration: none;

            }
            body{
                background-color : lightsteelblue;
            }
            h1{
                font-size: 72px;
                font-family: 'Times New Roman', Times, serif;
            }
        </style>
    </head>
    <body>

       
        <div class = "myDiv">
            <h1>Server Monitoring Diagnostics Tool</h1>
       
            

                <p> <a  href="{{ url_for('main.login') }}">Login</a> </p>
                <br>
                <br>
                <p><a href="{{ url_for('main.register') }}">Sign Up</a></p>
           
        </div>
    </body>


</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        li{
            font-size: 32px;
        }
        .title{
            text-align: center;
            font-size: 72px;
            font-family: 'Times New Roman', Times, serif;
        }
        .msg{
            display: table;
            margin: auto;
            color: rgb(235, 36, 36);
            padding: 10px;
            border-radius: 20px;
            background-color: rgb(252, 200, 200);
            border: thick solid red;
            font-weight: bolder;
        }
        .textBox{
            text-align: center;
            background-color: lightsteelblue;
        }
        body{
           background-color: lightsteelblue; 
        }
        p{
            font-size: 24px;
            
            font-family: 'Times New Roman', Times, serif;
        }
        #submit{
            background-color: #ffffff;
            border: solid rgb(133, 169, 215);
            border-radius: 5px;
            color: black;
            padding: 5px 22px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 24px;
            margin: 4px 2px;
            cursor: pointer;
            font-family: 'Times New Roman', Times, serif;
        }
        #submit:hover {
            background-color: rgb(170, 170, 170);
        }
        a{
            border: solid rgb(133, 169, 215);
                background-color: white;
                border-radius: 5px;
                margin : 100px;
                padding: 5px 18px;
                font-size: 24px;
                font-family: 'Times New Roman', Times, serif;
                
                color: black;
                text-decoration: none;

            }
        .backButton {
                border: thick solid rgb(127,165,215);
                background-color: aliceblue;
                border-radius: 10px;
                margin : 100px;
                padding: 10px;
                font-size: 40px;
                font-family: 'Times New Roman', Times, serif;
                color: black;
                text-decoration: none;
        }
        a:hover {
            background-color: rgb(170, 170, 170);
        }
    </style>
</head>
    <body>
        <br><br><a href="{{ url_for('main.index') }}" class="backButton">Back to Home</a>
        <h1 class = 'title'>Login</h1>
        
        {% with messages = get_flashed_messages() %}

        {% if messages %}
            <div class = 'msg'>
            

                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}

            </div>

        {% endif %}
        {% endwith %}
        

    <div class = 'textBox'>
        <form method="post">

            {{ form.hidden_tag() }}

            <p>
                {{ form.username.label }} <br>
                {{ form.username(size=32) }}<br>

                {% for error in form.username.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}

            </p>

            <p>
                {{ form.password.label }} <br>
                {{ form.password(size=32) }}<br>

                {% for error in form.password.errors %}
                    <span style="color: red;">[ {{ error }} ]</span>
                {% endfor %}
            </p>

            {{ form.submit }}
            <p><a href="{{ url_for('main.register') }}">Sign Up</a></p>
            <p style = "font-size: 18px;font-family: 'Times New Roman', Times, serif;">No Account? Sign Up here!</p>
        </form>
    </div>
    </body>

</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <style>
            .boxDiv{
                margin: auto;
                margin-top: 5%;
                padding: 20px;
                background-color: aliceblue;
                width: 400px;
                text-align: center;
            }
            .errorDiv {
                display: table;
                margin: auto;
                color: rgb(235, 36, 36);
                padding: 10px;
                border-radius: 20px;
                background-color: rgb(252, 200, 200);
                border: thick solid red;
                font-weight: bolder;
            }
            a{
                border: thick solid rgb(127,165,215);
                background-color: aliceblue;
                border-radius: 10px;
                margin : 100px;
                padding: 10px;
                font-size: 40px;
                font-family: 'Times New Roman', Times, serif;
                color: black;
                text-decoration: none;
            }
            a:hover {
                background-color: rgb(170, 170, 170);
            }
            body{
                background-color : lightsteelblue;
            }
            h1{
                font-size: 50px;
            }
            form{
                font-size: 25px;
            }
            input[type=text], input[type=password] {
                height: 30px;
                width: 300px;
                font-size: 25px;
            }
            input[type=submit] {
                font-size: 20px;
                color: black;
                cursor: pointer;
                border-radius: 15%;
                margin : 10px;
                padding: 10px;
            }
            input[type=submit]:hover {
                background-color: rgb(170, 170, 170);
            }
            
        </style>
    </head>
    <body>
        <br><br><a  href="{{ url_for('main.index') }}">Back to Home</a>
        <div class="boxDiv">
            <h1>Register</h1>

            {% with messages = get_flashed_messages() %}

            {% if messages %}
            <ul>

                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}

            </ul>
            {% endif %}
            {% endwith %}
            
            <form method="post">

                {{ form.hidden_tag() }}

                <p>
                    {{ form.username.label }}<br>
                    {{ form.username(size=32) }}<br>
                    {% for error in form.username.errors %}
                    <div class="errorDiv"><span style="color: red;"><b>{{ error }}</b></span></div>
                    {% endfor %}
                </p>
                <p>
                    {{ form.email.label }}<br>
                    {{ form.email(size=32) }}<br>
                    {% for error in form.email.errors %}
                    <div class="errorDiv"><span style="color: red;"><b>{{ error }}</b></span></div>
                    {% endfor %}
                </p>
                <p>
                    {{ form.password.label }}<br>
                    {{ form.password(size=32) }}<br>
                    {% for error in form.password.errors %}
                    <div class="errorDiv"><span style="color: red;"><b>{{ error }}</b></span></div>
                    {% endfor %}
                </p>
                <p>
                    {{ form.password2.label }}<br>
                    {{ form.password2(size=32) }}<br>
                    {% for error in form.password2.errors %}
                    <div class="errorDiv"><span style="color: red;"><b>{{ error }}</b></span></div>
                    {% endfor %}
                </p>

                <p>{{ form.submit() }}</p>
        </div>
    </body>

</html>

app/templates/settings.html
<!DOCTYPE html>
<html>


    <body>

        <h1>Account Settings</h1>

        <p>{{ current_user.username }}</p>

        {% if current_user.zip_key != None %}

        <form action="{{ url_for('main.set_zip_key') }}" method="post">

            {{ form.hidden_tag() }}

            {{ form.reset_key() }}

        </form>

        {% else %}

        <form action="{{ url_for('main.set_zip_key') }}" method="post">
            
            {{ form.hidden_tag() }}

            <p>
                {{ form.zip_key.label }} <br>
                {{ form.zip_key(size=32) }}<br>

                {% for error in form.zip_key.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}

            </p>

            {{ form.submit_key() }}

        </form>

        {% endif %}

        <p><a href="{{ url_for('main.dashboard') }}">Return to dashboard</a></p>

    </body>

</html>